### PR TITLE
Add a join message for new members

### PR DESCRIPTION
**Pull request by aalberg**

### CODE REVIEW

**Comment by teejusb** [comment]
I think we only want the "Add join messages for members" commit?

**Comment by aalberg** [comment]
I don't know if there's a point cherrypicking specific commits, the diff shows what we want changed. You've also previously merged in commits that are just me merging from your branch to mine. Not sure what the "proper" way to use git here is though.

**Comment by aalberg** [comment]
Poking around some more, the options seem to be:
1. Accept that there are going to be extra commit messages for merging across branches
2. Manually pull my master branch, cherry pick the commits you want, push, and close the PR: https://stackoverflow.com/questions/7217031/github-accept-pull-request-but-only-some-commits

The first seems like less work.

**Comment by teejusb** [comment]
Yeah you have need to either merge stuff (and take the hit with extra commits). Alternatively you can rebase so that your pending commits actually branch off from "head" instead of where you originally forked from.

**Pull request merged**
